### ISSUE TITLE
Make a ZIM of Klexikon.de

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#100]
_From @kelson42 on September 17, 2016 8:56_

They do not seem to use the visual editor, this problem should be fixed first.

_Copied from original issue: openzim/mwoffliner#21_

**Comment by kelson42** [comment]
Here was my command:
```
mwoffliner --mwApiPath="api.php" --mwUrl="https://klexikon.zum.de/" --adminEmail="kelson@kiwix.com" --localParsoid --verbose
```

and I got the following error
```
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/watch-icon-loading.gif
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/user-icon.png
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/watch-icons.png
Executing command : pngquant --verbose --strip --nofs --force --ext=".xd4i9.png" "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png" "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png"; fi
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png
Saving favicon.png...
Downloading https://klexikon.zum.de/api.php?action=query&meta=siteinfo&format=json...
Executing command : gifsicle --verbose --colors 64 -O3 "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif" -o "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif" "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif"; fi
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:150:11)
    at Object.urlParse [as parse] (url.js:144:13)
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2083:29
    at async.retry (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:176:7)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:676:51
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:723:17

```

**Comment by kelson42** [comment]
A first version has been made here https://download.kiwix.org/zim/other/klexikon_de_all_2018-09.zim and will be updated around one time a month.

**Comment by Popolechien** [comment]
Reopening the ticket as the scraper has been failing repeatedly for the past half-year.

**Comment by Popolechien** [comment]
Had a quick look at the logs and it's always a timeout issue. Does this mean the problem is on the Klexikon side?

**Comment by kelson42** [comment]
Yes klexikon backend is slow. We have a tciket in mwoffliner already for this timeout problems. No value to keep one open here.

**Comment by Popolechien** [comment]
Ah, https://github.com/openzim/mwoffliner/issues/660 I think

**Comment by Spielmops** [comment]
There is the last successful created version of Klexicon from 2020/20/06 in the archiv. My idea: put that version into the download-list until there is a new version.

Spielmops
