### ISSUE TITLE
codegolf.stackexchange.com_en is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1003]
### Recipe URL

https://farm.openzim.org/recipes/codegolf.stackexchange.com_en

### Last log lines

```true
[ThreadPoolExecutor-0_0::2024-05-16 11:15:02,159] INFO:Extracting codegolf.stackexchange.com.7z
[MainThread::2024-05-16 11:15:21,070] INFO:removed badges headers
[MainThread::2024-05-16 11:15:21,222] INFO:sorted Badges by UserId
[MainThread::2024-05-16 11:15:21,361] INFO:removed users headers
[MainThread::2024-05-16 11:15:22,027] INFO:merged both sets
[MainThread::2024-05-16 11:15:22,405] INFO:removed comments headers
[MainThread::2024-05-16 11:15:22,739] INFO:sorted Comments by UserId
[MainThread::2024-05-16 11:15:24,335] INFO:removed posts headers
[MainThread::2024-05-16 11:15:27,379] INFO:merged Posts and Comments
[MainThread::2024-05-16 11:15:29,795] INFO:split Posts-Comments by PostType
[MainThread::2024-05-16 11:15:30,055] INFO:Extracted Post IDs and titles into CSV
[MainThread::2024-05-16 11:15:30,272] INFO:sorted Posts-Comments (questions) by Id
[MainThread::2024-05-16 11:15:31,701] INFO:sorted Posts-Comments (answers) by ParentId
[MainThread::2024-05-16 11:15:31,765] INFO:removed postlinks headers
[MainThread::2024-05-16 11:15:31,781] INFO:sorted PostLinks by PostId
[MainThread::2024-05-16 11:15:31,843] INFO:sorted named post links by RelatedPostId
[MainThread::2024-05-16 11:15:34,308] INFO:Prepared dumps completed.
[MainThread::2024-05-16 11:15:34,787] INFO:PROGRESS: 3.5% – Step 1/7: Prep -- 10/10
[MainThread::2024-05-16 11:15:34,984] ERROR:FAILED. An error occurred: Title is too long.
[MainThread::2024-05-16 11:15:34,984] ERROR:Title is too long.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.1.2-py3.8.egg/sotoki/entrypoint.py", line 348, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.1.2-py3.8.egg/sotoki/scraper.py", line 173, in run
    return self.start()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.1.2-py3.8.egg/sotoki/scraper.py", line 208, in start
    Global.creator.start()
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 156, in start
    self.validate_metadata(name, value)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 185, in validate_metadata
    validate_title(name, value)  # pyright: ignore
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/metadata.py", line 47, in validate_title
    raise ValueError(f"{name} is too long.")
ValueError: Title is too long.
[MainThread::2024-05-16 11:15:34,984] DEBUG:Removing /codegolf.stackexchange.com_us3wsybx
```

### How many times the recipe failed in a row?

Once

### How many ZIM have been produced before failure?

Zero

### Which action did you undertake so far?

I have disabled the recipe for now

### What's next?

This has to be fixed by dev team (upstream scraper / zimfarm problem)

### More details

Title is supposed to be automatically computed, i.e. "Code Golf Stack Exchange", which is not too long

**Comment by benoit74** [comment]
Only concern seems to be that automatic title is indeed too long. I configured one manually.

**Comment by benoit74** [comment]
Indeed, file produced successfully: https://library.kiwix.org/#lang=&q=code+golf
