### ISSUE TITLE
Wiki Doc

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1071]
- Website URL: https://www.wikidoc.org/
- License: **CC-BY-SA** 
- Desired ZIM Title: **Wiki Doc**
- Desired ZIM Description: _The Living Textbook of Medicine_
- Desired ZIM Icon –png (URL or attach one): https://www.wikidoc.org/images/6/6e/An1.jpg
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by benoit74** [comment]
I tried to run mwoffliner locally and it failed with 
```
[error] [2024-10-07T07:51:01.434Z] Unable to retrieve js/css dependencies for article 'CSA Trust': nosuchrevid
[log] [2024-10-07T07:51:01.434Z] Exiting with code [1]
[log] [2024-10-07T07:51:01.434Z] Deleting temporary directory [/tmp/mwoffliner-1728287394504]
file:///tmp/mwoffliner/lib/Downloader.js:570
            throw new Error(errorMessage);
                  ^

Error: Unable to retrieve js/css dependencies for article 'CSA Trust': nosuchrevid
    at Downloader.getModuleDependencies (file:///tmp/mwoffliner/lib/Downloader.js:570:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:250:45
```

**Comment by benoit74** [comment]
See https://github.com/openzim/mwoffliner/issues/2091

**Comment by Popolechien** [comment]
Created https://farm.openzim.org/recipes/wikidoc.org_en_all - awaiting review

Note: we probably need to check API path and some CSS would be welcome to remove the search bar

<img width="1396" height="231" alt="Image" src="https://github.com/user-attachments/assets/de68c346-4526-433f-a20b-0b8d2423fcaa" />

**Comment by benoit74** [comment]
To remove searchbar I would prefer someone with edits right on the wiki adds `class="noprint"` on all HTML elements which must not be printed (and will automatically not be shown in the ZIM).

Recipe config updated and requested

**Comment by Popolechien** [comment]
Task failed with missing API https://farm.openzim.org/pipeline/57930fce-b670-439d-89dd-5600d5c36b1b

**Comment by benoit74** [comment]
Recipe fixed and requested again, looks like I was too obsessed by the search bar in last review 🤣

**Comment by Popolechien** [comment]
Task failed again https://farm.openzim.org/pipeline/da3a65e0-7b02-4c13-a93f-019310c7baab

**Comment by benoit74** [comment]
```
 Error: Too many files failed to download:
```

Upstream issue is https://github.com/openzim/mwoffliner/issues/2679
