### ISSUE TITLE
English Wikivoyage run overdue (time sensitive)

### ISSUE THREAD

**Issue by Jaifroid** [openzim/zim-requests#1129]
The periodicity of the ZIM Farm recipe https://farm.openzim.org/recipes/wikivoyage_en_all is set to monthly, but the last run was 16th June 2024.

Ideally, I need a new version for the Wikivoyage by Kiwix app update before the code-signing certificate expires in a couple of weeks... (to buy time in adapting to the new code-signing reigime). Thanks.

**Comment by kelson42** [comment]
I will relaunxh it with version dev (1.14.0) of MWoffliner, but we will have a ZIM which will be arounf 30% bigger, this is currently a regression we try to fix.

**Comment by Jaifroid** [comment]
@kelson42 Thank you. Let's see...

**Comment by Jaifroid** [comment]
The resulting ZIM size is fine at 875MB. However it breaks our Restricted mode (aka JQuery mode) because it has all the Details sections set with attribute 'style="display: none;"` (see screenshot at bottom). Since we don't run JS in Restricted mode, it means these ZIMs become inaccessible to users who do not have JS enabled in their browser or (in the case of Kiwix JS) cannot run a Service Worker.

This issue has been a longstanding one that was partially fixed: see https://github.com/openzim/mwoffliner/issues/962, https://github.com/openzim/mwoffliner/issues/838, https://github.com/openzim/mwoffliner/issues/952 and (related) https://github.com/openzim/mwoffliner/issues/1033. Another closely related: https://github.com/openzim/mwoffliner/issues/1915.

This regression (but it's worse, see next paragraph) has crept back in probably with the new endpoint. The logic should be: the HTML has all sections open by default, and they should only be closed by a script that will run when JS is enabled. This makes the most accessible ZIM type for mwOffliner.

The regression is much worse now because the entire details-summary block is now hidden, instead of merely closed. It should never use inline `display: none;` rule, and should rely only on the `open` attribute.

@kelson42, @audiodude  Where should I report this regression? In mwOffliner Repo or wp1?

![image](https://github.com/user-attachments/assets/c175905d-93ea-4d90-9277-6e1d99d27152)

I can work around this in the reader for the upcoming Wikivoyage release with a temporary patch to force-unhide, but it should be fixed in the scraper for a more universal solution.

**Comment by kelson42** [comment]
@Jaifroid We won't provide collapsablible sections anymore as this was a feature of older "mobile-section". This seems therefore some kind of leftover which shoukd be removed IMHO. Please open tocket in MWoffliner.

**Comment by Jaifroid** [comment]
@kelson42 OK. I suppose https://github.com/openzim/mwoffliner/issues/1915 should be closed as won't fix in that case. I mean, it's not hard to substitute the sections and headers for detail-summary tags in case there's any desire to keep that feature, but to be honest I never found it useful to have all the sections closed, even in the mobile version.

**Comment by Jaifroid** [comment]
@kelson42 The English Wikivoyage recipe has been running on `mwoffliner:dev` monthly since you kindly re-eanabled it in August. But in the last two months (Sep and Oct) it has only succeeded in producing the `nopic` version. It keeps failing to produce `maxi`, which is the one I need to update the Wikivoyage app. See log below.

Is there anything we can do about this? I'm keen to get a new Wikivoyage out especially because the last version had some issues in KJS / PWA that I hadn't fully caught and now they are fixed, so it would be a buch better UX than the currently published app version.

I looked at the logs on https://farm.openzim.org/pipeline/53d49603-fd60-4933-b7f3-5b8130b29805/debug, and the failure seems to be reported as:
```
An error was encountered in a non-retryable streaming request.
[error] [2024-10-04T23:43:02.196Z] Cache error while uploading object: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
    at throwDefaultError (/tmp/mwoffliner/node_modules/@smithy/smithy-client/dist-cjs/index.js:840:20)
    at /tmp/mwoffliner/node_modules/@smithy/smithy-client/dist-cjs/index.js:849:5
    at de_CommandError (/tmp/mwoffliner/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4743:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /tmp/mwoffliner/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /tmp/mwoffliner/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:482:18
    at async /tmp/mwoffliner/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /tmp/mwoffliner/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:174:18
    at async /tmp/mwoffliner/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
    at async /tmp/mwoffliner/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: 'F46C3F407538CF32:B',
    extendedRequestId: 'oG4WkdG8LALy860KgaUTw18qofngQZNZg39fIB5nw/M3ZOxSudf2AcKLEFPlbO0bPEnQzTB7eU2k',
    cfId: undefined
  },
  Code: 'RequestTimeTooSkewed',
  RequestTime: '20241004T232801Z',
  ServerTime: '2024-10-04T23:43:02Z',
  MaxAllowedSkewMilliseconds: '900000',
  RequestId: 'F46C3F407538CF32:B',
  HostId: 'oG4WkdG8LALy860KgaUTw18qofngQZNZg39fIB5nw/M3ZOxSudf2AcKLEFPlbO0bPEnQzTB7eU2k',
  CMReferenceId: 'MTcyODA4NTM4MTkzOSAzOC4xNDYuNDAuMTA3IENvbklEOjMyNDAyNDg0Ny9FbmdpbmVDb25JRDozMDI5NDI2L0NvcmU6OTM='
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
```

**Comment by audiodude** [comment]
This doesn't look like a problem with `mwoffliner` itself, but rather the container environment. Specifically:

```
  RequestTime: '20241004T232801Z',
  ServerTime: '2024-10-04T23:43:02Z',
```

Looks bad.

I'll try running it locally and see if I can send you a ZIM.

**Comment by audiodude** [comment]
It ran fine for me on 1.14-dev. Here's the ZIM: https://www.dropbox.com/scl/fi/idcb6c96gzigmc5mcm45x/wikivoyage_en_all_maxi_2024-10.zim?rlkey=e5q52jymxxa5fu316edl3bwit&st=l2wjaik0&dl=0

This is clearly some kind of operational/environment issue with zimfarm.

**Comment by benoit74** [comment]
> This doesn't look like a problem with mwoffliner itself, but rather the container environment. Specifically:

At least `mwoffliner1` (which is the VM which ran last task) has proper time clock, up-to-date.

Could it be that the container itself has improper ntc clock and get slowly skewed as it progress?I don't think so, it seems weird a container can "loose" ~20 mins during a 3 hours job.

What I see in the logs are many message like `@smithy/node-http-handler:WARN - socket usage at capacity=50 and 115 additional requests are enqueued.`.

To me this is the root cause of the problem, and it is a software bug. I understand this message as the software has started many HTTP requests and they are getting delayed. And hence the skew time between request time and server time from my PoV. Classic async issue in Node.JS from my PoV, where one can easily get bitten by all this asynchronous logic which has many advantages but some drawbacks. 

And of course this problem occur randomly since it depends on your connectivity with the upstream. Travis connectivity to AWS is probably better than the connectivity from `mwoffliner1` / wikimedia foundation datacenter.

I'll open another issue to track this problem.

**Comment by benoit74** [comment]
Upstream issue: https://github.com/openzim/mwoffliner/issues/2092

**Comment by Jaifroid** [comment]
Thanks, guys, for diagnosing this, and @audiodude for the updated ZIM file. I've downloaded and done some quick tests on this, and it looks fine.

Would anyone have any objections to my uploading it to download.kiwix.org (Wikivoyage folder) so I can build the Wikivoyage app (via GH Actions)?

**Comment by benoit74** [comment]
No objection on my side.

**Comment by Jaifroid** [comment]
OK, it seems my credentials only give me access to the nightly and release directories (for software), but not to the zim directory, so I can't in fact upload the new Wikivoyage ZIM to download.kiwix.org. @benoit74 Is this something you could kindly do for me? The ZIM to upload to `/zim/wikivoyage` is in @audiodude's dropbox linked in https://github.com/openzim/zim-requests/issues/1129#issuecomment-2398458748 . Many thanks! 😊

**Comment by benoit74** [comment]
File is available in production at https://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_maxi_2024-10.zim

It will soon be automatically indexed in the catalog.

**Comment by Jaifroid** [comment]
So, since October I haven't been able to update the Wikivoyage (desktop) app, as the runs on zimfarm keep failing. Looking at the latest run, which stalled for 10 days (!), it succeeded very quickly in producing a `nopic` version, and then just got stuck. It doesn't seem to be the timing issue we had before (unless I'm not looking at detailed-enough logs). Here is what I see:

![Image](https://github.com/user-attachments/assets/1f24c6dd-fb28-4419-b40e-0761c2f7efff)

Source: https://farm.openzim.org/pipeline/17080574-c222-4c2b-9753-7932e839a0c6/debug

The runs in-between October and now have all failed as well. I realize Wikivoyage is probably the least of the problems just now, but I thought I should update this issue.

**Comment by benoit74** [comment]
I've identified and fixed multiple issues around image processing in mwoffliner, and what you mention here is a known symptom of the issues I've fixed.

PRs are under review, hopefully they will get merged and released soon.

**Comment by Jaifroid** [comment]
Thanks for the update, @benoit74 ! Fingers crossed! 🤞

**Comment by benoit74** [comment]
I've started the recipe again with 1.14.1, targeting dev environment first to check ZIM before pushing to prod.

**Comment by benoit74** [comment]
@Jaifroid can you please have a look at https://dev.library.kiwix.org/#lang=&q=travel

If everything is fine, I will request them in prod (and probably quite soon request other wiki_voyage ZIMs as well)

**Comment by Jaifroid** [comment]
Thank you @benoit74 , I'm downloading the full version now.

**Comment by Jaifroid** [comment]
I've looked through the maxi version, and it is a great improvement in lots of ways. The articles now all have titles, and the text appears to be fully present in all the articles I've randomly sampled, with adequately sized images. I would be able to use this ZIM to produce an updated release of the Wikipedia desktop app (Electron).

The ZIM still contains some issues that are the subject of issues reported in the mwOffliner repo. These mostly relate to the included CSS. The main issues I noted are that the font is tiny, and that some external hyperlinks with geo-markers are rendered as white on white, and so are effectively invisible in the app. See screenshot below, made with the Browser Extension.

**However, because the Electron app and the PWA provides its own stylesheets for Wikimedia ZIMs** (for the purpose of providing transformation between mobile, desktop and dark-themed styles, these issues are fully masked (worked around) in the app and the PWA, and therefore are not in ay sesee a blocker to my releasing a new app. Compare the display of the same article in the PWA (bottom screenshot).

You may wish to hold off on producing the Android custom apps with these ZIMs, until those small issues are ironed out. But I would be keen to have at least the maxi ZIM moved to production so that I ca automatically build the different app flavours (Windows and Linux).

There is one display issue I need to fix in the PWA before release (repeated titles), but that's entirely an issue with my code and I'll clean that up shortly in any case.

**In Browser Extension:**

![Image](https://github.com/user-attachments/assets/3cd22b64-4859-4056-a555-b4d30bf3f35e)

**In PWA/Electron app:**

![Image](https://github.com/user-attachments/assets/960b3e0a-b729-491e-9320-84382bb2c2e8)

**Comment by kelson42** [comment]
In addition to what has been reported by @Jaifroid (in particular the white on white problem), we have a regression around handling of (certain?) collapsable sections, see for example ![image](https://github.com/user-attachments/assets/a94a6e53-bc18-441e-8acd-c88be425ce29) which is not uncollapsable.

In addition, but this is not new and has been discussed already, the ZIM are around 20% bigger than before (with @audiodude) which is in general a problem and a very serious one (blocker?) for mobile custom apps.

**Comment by Jaifroid** [comment]
@kelson42 Although it looks like there is an uncollapsed section in your screenshot, actually from what I can tell all the info is there, but the white space occupied by the white-on-white links causes it to appear that way. Compare the same page in KJS Browser Extension (uncorrected CSS) and in Kiwix PWA (uses own mobile stylesheet) in this screenshot:

![Image](https://github.com/user-attachments/assets/a10ad897-712f-42ca-b2f7-66d805ece9e2)

The issue is "just" that we need to include a new stylesheet or tweak the existing ones (it's probably just a rule or two that need tweaking). Ideally, we'd have a proper ZIM-level theming system that would allow application of the different CSS styles offered by Wikimedia sites (Vector, Modern, Minerva, etc.).

(Maybe both these comments should be moved to https://github.com/openzim/mwoffliner/issues/2085 to provide more info there.)

**Comment by Jaifroid** [comment]
PS As speculated in https://github.com/openzim/mwoffliner/issues/2085, this white-on-white affecting only geo: links is likely to be caused by the code in mwOffliner that transforms existing Wikivoyage place markers into the little globe icon. It may be sufficient just to fix that code. My guess is that it applies a CSS class that doesn't exist in the HTML/CSS retrieved from the mobile-html API, or one that inadvertently cancels existing format of the element. We may not even need to tweak the stylesheets.

**Comment by benoit74** [comment]
I'm experimenting with https://farm.openzim.org/recipes/wikivoyage_en_all_desktop-renderer which is same recipe but with WikimediaDesktop renderer instead of WikimediaMobile ; to me it looks like it would solve both issues above with minimal drawbacks (or at least I did not witnessed them yet). The ZIM is less optimized for mobile but still looks very great because it is still responsive. And the fact it is less optimized for mobile looks even like an advantage since it means it will also render well on tablets and desktops (while the WikimediaMobile version looks "weird").

I hope I'm not stirring up any old demons regarding the choice of API/renderer. 🤣

**Comment by Jaifroid** [comment]
I'm open to anything at this stage of affairs! 😱

**Comment by benoit74** [comment]
New ZIMs with WikimediaDesktop are available: https://dev.library.kiwix.org/#lang=&q=travel

- wikivoyage_en_all_nopic_2025-02 and wikivoyage_en_all_maxi_2025-02: WikimediaMobile API / renderer
- wikivoyage_en_all-desktop-renderer_nopic_2025-02 and wikivoyage_en_all-desktop-renderer_maxi_2025-02: WikimediaMobile API / renderer

To me they are superior to WikimediaMobile in all dimensions: less bugs and more responsive to all screen sizes. What do I miss? @Popolechien @kelson42 any input?

**Comment by benoit74** [comment]
Tested as well on Kiwix-Android, they work well.

**Comment by Jaifroid** [comment]
Hallelujah! This does fix a lot of things. It works perfectly in both the KJS Browser extension and in the PWA.

Is this the solution for Wikipedia scrapes too??? Congratulations! 🎉🍾

**Comment by benoit74** [comment]
> Is this the solution for Wikipedia scrapes too???

🤫

Files have been updated in production and are back to normal monthly schedule (hopefully ^^)
