### ISSUE TITLE
ted_topic_infectious-generosity is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1133]
### Recipe URL

https://farm.openzim.org/recipes/ted_topic_infectious-generosity

### Last log lines

```true
Attempting to update yt-dlp…
Requirement already satisfied: yt-dlp in /usr/local/lib/python3.12/site-packages (2024.7.9)
Collecting yt-dlp
  Downloading yt_dlp-2024.8.6-py3-none-any.whl.metadata (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 kB 7.3 MB/s eta 0:00:00
Requirement already satisfied: brotli in /usr/local/lib/python3.12/site-packages (from yt-dlp) (1.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/site-packages (from yt-dlp) (2024.7.4)
Requirement already satisfied: mutagen in /usr/local/lib/python3.12/site-packages (from yt-dlp) (1.47.0)
Requirement already satisfied: pycryptodomex in /usr/local/lib/python3.12/site-packages (from yt-dlp) (3.20.0)
Requirement already satisfied: requests<3,>=2.32.2 in /usr/local/lib/python3.12/site-packages (from yt-dlp) (2.32.3)
Requirement already satisfied: urllib3<3,>=1.26.17 in /usr/local/lib/python3.12/site-packages (from yt-dlp) (2.2.2)
Requirement already satisfied: websockets>=12.0 in /usr/local/lib/python3.12/site-packages (from yt-dlp) (12.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.32.2->yt-dlp) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests<3,>=2.32.2->yt-dlp) (3.7)
Downloading yt_dlp-2024.8.6-py3-none-any.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 54.6 MB/s eta 0:00:00
Installing collected packages: yt-dlp
  Attempting uninstall: yt-dlp
    Found existing installation: yt-dlp 2024.7.9
    Uninstalling yt-dlp-2024.7.9:
      Successfully uninstalled yt-dlp-2024.7.9
Successfully installed yt-dlp-2024.8.6
[ted2zim::2024-08-09 00:06:43,331] INFO:Starting scraper with:
  langs: zh-tw, zh-cn, en, zh, fr, fr-ca, de
  subtitles : all
  video format : webm
[ted2zim::2024-08-09 00:06:43,331] INFO:Testing S3 Optimization Cache credentials
[ted2zim::2024-08-09 00:06:45,968] INFO:Using cache: s3.us-west-1.wasabisys.com with bucket: org-kiwix-ted
[ted2zim::2024-08-09 00:06:45,968] DEBUG:Fetching video links for topic: infectious generosity
[ted2zim::2024-08-09 00:06:45,968] DEBUG:Fetching page 0 of topic infectious generosity
[ted2zim::2024-08-09 00:06:47,436] DEBUG:1 video(s) found on current page
[ted2zim::2024-08-09 00:06:47,436] DEBUG:extract_info_from_video_page: https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year
[ted2zim::2024-08-09 00:06:49,843] WARNING:player data has no entry for en: list index out of range
[ted2zim::2024-08-09 00:06:49,844] DEBUG:Using h264 resource link for bitrate=1200
[ted2zim::2024-08-09 00:06:51,335] DEBUG:Successfully inserted video 126808 into video list
[ted2zim::2024-08-09 00:06:51,335] DEBUG:Searching info for the video in 6 other language(s)
[ted2zim::2024-08-09 00:06:51,335] DEBUG:extract_info_from_video_page: https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=zh-tw
[ted2zim::2024-08-09 00:06:53,730] DEBUG:Video at https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=zh-tw has not yet been translated into zh-tw
[ted2zim::2024-08-09 00:06:53,730] DEBUG:extract_info_from_video_page: https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=zh-cn
[ted2zim::2024-08-09 00:06:56,194] DEBUG:Video at https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=zh-cn has not yet been translated into zh-cn
[ted2zim::2024-08-09 00:06:56,194] DEBUG:extract_info_from_video_page: https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=zh
[ted2zim::2024-08-09 00:06:58,515] DEBUG:Video at https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=zh has not yet been translated into zh
[ted2zim::2024-08-09 00:06:58,515] DEBUG:extract_info_from_video_page: https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=fr
[ted2zim::2024-08-09 00:07:00,316] DEBUG:Video at https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=fr has not yet been translated into fr
[ted2zim::2024-08-09 00:07:00,317] DEBUG:extract_info_from_video_page: https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=fr-ca
[ted2zim::2024-08-09 00:07:02,871] DEBUG:Video at https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=fr-ca has not yet been translated into fr-ca
[ted2zim::2024-08-09 00:07:02,871] DEBUG:extract_info_from_video_page: https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=de
[ted2zim::2024-08-09 00:07:05,014] DEBUG:Video at https://ted.com/talks/the_ted_interview_how_bill_gates_spends_9_billion_a_year?language=de has not yet been translated into de
[ted2zim::2024-08-09 00:07:05,015] DEBUG:Seen the_ted_interview_how_bill_gates_spends_9_billion_a_year
[ted2zim::2024-08-09 00:07:05,015] DEBUG:Fetching page 1 of topic infectious generosity
[ted2zim::2024-08-09 00:07:06,503] DEBUG:0 video(s) found on current page
[ted2zim::2024-08-09 00:07:06,504] INFO:Total video links found in infectious generosity: 1
[ted2zim::2024-08-09 00:07:06,504] DEBUG:Successfully scraped infectious generosity
[ted2zim::2024-08-09 00:07:06,505] DEBUG:Downloading How Bill Gates spends $9 billion a year
[ted2zim::2024-08-09 00:07:06,943] ERROR:Could not download from https://py.tedcdn.com/consus/projects/00/69/88/001/products/2024v-the-ted-interview-bill-gates-001-fallback-3f17d5df-d4c6-45ff-b851-85a04bb8bce0-1200k.mp4 for /output/tmpild_xvxz/videos/126808/video.mp4
[ted2zim::2024-08-09 00:07:06,943] DEBUG:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ted2zim/scraper.py", line 1115, in download_video_files
    save_large_file(video_link, org_video_file_path)
  File "/usr/local/lib/python3.12/site-packages/zimscraperlib/download.py", line 127, in save_large_file
    subprocess.run(
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/env', 'wget', '-t', '5', '--retry-connrefused', '--random-wait', '-O', '/output/tmpild_xvxz/videos/126808/video.mp4', '-c', 'https://py.tedcdn.com/consus/projects/00/69/88/001/products/2024v-the-ted-interview-bill-gates-001-fallback-3f17d5df-d4c6-45ff-b851-85a04bb8bce0-1200k.mp4']' returned non-zero exit status 8.
[ted2zim::2024-08-09 00:07:07,058] DEBUG:Stats: 0 videos ok, 1 videos failed
[ted2zim::2024-08-09 00:07:07,058] ERROR:FAILED. An error occurred: No successfull video, aborting ZIM creation
[ted2zim::2024-08-09 00:07:07,058] ERROR:No successfull video, aborting ZIM creation
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ted2zim/entrypoint.py", line 205, in main
    scraper.run()
  File "/usr/local/lib/python3.12/site-packages/ted2zim/scraper.py", line 1346, in run
    raise Exception("No successfull video, aborting ZIM creation")
Exception: No successfull video, aborting ZIM creation
```

### How many times the recipe failed in a row?

Twice

### How many ZIM have been produced before failure?

One

### Which action did you undertake so far?

None, I recommend to wait for next run on periodic scheduling to confirm there is an issue

### What's next?

This has to be monitored by content team

### More details

This topic has only one video. It succeeded once few months ago, but now the only video in the topic is failing to be downloaded. This is an TED issue, nothing we can fix on our side. Let's wait one quarter and check again what happens, this issue is here to track that we are aware about the issue.

**Comment by kelson42** [comment]
@benoit74 The recipe seems to have vanished. Does this issue deserve an update? An upstream issue?

**Comment by benoit74** [comment]
Closing, there was too few / no videos so we've deleted the recipe.
