### ISSUE TITLE
devhints.io_en_all is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#1185]
### Recipe URL

https://farm.openzim.org/recipes/devhints.io_en_all

### Last log lines

```
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 688, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 417, in run
    res = warc2zim(warc2zim_args)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/main.py", line 168, in main
    return converter.run()
           ^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 276, in run
    validate_title("Title", self.title)
  File "/app/zimit/lib/python3.12/site-packages/zimscraperlib/zim/metadata.py", line 57, in validate_title
    raise ValueError(f"{name} is too long.")
ValueError: Title is too long.

```

### How many times the recipe failed in a row?

Twice

### How many ZIM have been produced before failure?

Many

### Which action did you undertake so far?

I have disabled the recipe for now

### What's next?

This has to be fixed by content team

### More details

For some reason, title is now `Dev Hints - Bash scripting cheatsheet` while it was `Bash scripting cheatsheet`.

I don't get why:
- we have a new title without any discussions on Github (or did I missed it?)
- we have a new title which is too long (at least it won't be possible anymore now that the 30 chars limit is enforced at Zimfarm level)
- we have a new title which is just as bad as the former one (devhints.io is not **Bash** scripting cheatsheet, but cheatsheet about various "software things")

I also don't get why this recipe is scheduled for monthly update while it looks like the website is barely updated (or maybe even not updated at all, at least x.com account has no activity since 2021). A quarterly update is IMHO way enough.

I've disabled the recipe for now.

**Comment by benoit74** [comment]
Recipe fixed

**Comment by benoit74** [comment]
File ready in prod
