### ISSUE TITLE
2.8 million Missing articles in the latest wikipedia_en_all_nopic?

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#207]
Flagged from a user: wikipedia_en_all_nopic_2019-10.zim is listed as having 3.1 million articles instead of 5.9M.
![20191111_234253](https://user-images.githubusercontent.com/21675885/68662086-6e9a3d00-053c-11ea-8bac-efa8a8f6fc26.jpg)

**Comment by kelson42** [comment]
@rgaudin Could you share with us the log of this scrape please?

**Comment by rgaudin** [comment]
I have no way to certify that the task [5d5c519f1339d1137618f4b1](https://farm.openzim.org/tasks/5d5c519f1339d1137618f4b1) (link may not work as zimfarm is _down_ at the moment) is the one which created that ZIM file but it's the only recent one which attempted to run it. It was started on August 20th.

[Full log file](https://logs.warehouse.farm.openzim.org/mwoffliner_5d5c519f1339d1137618f4b1.log.xz)

Last lines of logs:

```
T:106414; Set article indexes
set index
T:106419; Resolve mimetype
T:106423; create title index
T:106445; 14336321 title index created
T:106445; 19599 clusters created
T:106445; fill header
T:106455; write zimfile :
T:106455;  write header
T:106455;  write mimetype list
T:106455;  write url prt list
T:106464;  write title index
T:106471;  write directory entries
T:106493;  write cluster offset list
T:106493;  write cluster data
T:106494; 1000/19599
T:106496; 2000/19599
T:106498; 3000/19599
T:106500; 4000/19599
T:106502; 5000/19599
T:106503; 6000/19599
T:106505; 7000/19599
T:106507; 8000/19599
T:106509; 9000/19599
T:106511; 10000/19599
T:106512; 11000/19599
T:106514; 12000/19599
T:106516; 13000/19599
T:106518; 14000/19599
T:106519; 15000/19599
T:106521; 16000/19599
T:106523; 17000/19599
T:106525; 18000/19599
T:106526; 19000/19599
T:106572;  write checksum
T:106572; finish
[log] [2019-08-22T04:24:57.144Z] Summary of scrape actions: {
	"files": {
		"success": 30862,
		"fail": 0
	},
	"articles": {
		"success": 5913897,
		"fail": 0
	},
	"redirects": {
		"written": 8391537
	}
}
[log] [2019-08-22T04:24:57.155Z] Finished dump
[log] [2019-08-22T04:24:57.160Z] Doing dump
[log] [2019-08-22T04:24:57.163Z] Writing zim to [/output/wikipedia_en_all_nopic_2019-08.zim]
[log] [2019-08-22T04:24:57.164Z] Flushing redis file store
[log] [2019-08-22T04:24:57.403Z] Found [4] stylesheets to download
[log] [2019-08-22T04:24:57.403Z] Downloading stylesheets and populating media queue
[log] [2019-08-22T04:24:57.464Z] Downloaded stylesheets
[log] [2019-08-22T04:24:57.465Z] Saving favicon.png...
[log] [2019-08-22T04:24:57.473Z] Flushing Redis DBs
[log] [2019-08-22T04:24:57.473Z] Exiting with code [2]
[log] [2019-08-22T04:24:57.473Z] Deleting tmp dump dir [/tmp/mwo-dump-1566331300390]
Failed to run mwoffliner after [116598s]: {
	"stack": "Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at Object.spawn (child_process.js:551:9)\n    at exec2 (/tmp/mwoffliner/node_modules/imagemagick/imagemagick.js:24:25)\n    at Object.exports.convert (/tmp/mwoffliner/node_modules/imagemagick/imagemagick.js:253:10)\n    at Promise (/tmp/mwoffliner/lib/mwoffliner.lib.js:423:47)\n    at new Promise (<anonymous>)\n    at resizeFavicon (/tmp/mwoffliner/lib/mwoffliner.lib.js:422:28)\n    at /tmp/mwoffliner/lib/mwoffliner.lib.js:439:28\n    at Generator.next (<anonymous>)\n    at /tmp/mwoffliner/lib/mwoffliner.lib.js:9:71\n    at new Promise (<anonymous>)\n    at __awaiter (/tmp/mwoffliner/lib/mwoffliner.lib.js:5:12)\n    at saveFavicon (/tmp/mwoffliner/lib/mwoffliner.lib.js:419:20)\n    at /tmp/mwoffliner/lib/mwoffliner.lib.js:337:23\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/mwoffliner.lib.js:6:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "spawn ENOMEM",
	"errno": "ENOMEM",
	"code": "ENOMEM",
	"syscall": "spawn"
}


**********

spawn ENOMEM

**********
```

**Comment by kelson42** [comment]
@rgaudin no the correct log

**Comment by rgaudin** [comment]
Here's the correct task: [5dad76a6efd26e8d5d6a6c75](https://farm.openzim.org/tasks/5dad76a6efd26e8d5d6a6c75). Started Oct 21, finished Oct 26th.

Full Log: https://logs.warehouse.farm.openzim.org/mwoffliner_5dad76a6efd26e8d5d6a6c75.log.xz

End of log:

```
T:392883; Set article indexes
set index
T:392884; Resolve mimetype
T:392886; create title index
T:392901; 7611238 title index created
T:392901; 40756 clusters created
T:392901; fill header
T:392905; write zimfile :
T:392905;  write header
T:392905;  write mimetype list
T:392905;  write url prt list
T:392908;  write title index
T:392911;  write directory entries
T:392924;  write cluster offset list
T:392924;  write cluster data
T:392929; 1000/40756
T:392934; 2000/40756
T:392940; 3000/40756
T:392945; 4000/40756
T:392949; 5000/40756
T:392954; 6000/40756
T:392963; 7000/40756
T:392970; 8000/40756
T:392982; 9000/40756
T:392990; 10000/40756
T:392997; 11000/40756
T:393003; 12000/40756
T:393013; 13000/40756
T:393022; 14000/40756
T:393030; 15000/40756
T:393037; 16000/40756
T:393045; 17000/40756
T:393055; 18000/40756
T:393062; 19000/40756
T:393070; 20000/40756
T:393077; 21000/40756
T:393088; 22000/40756
T:393096; 23000/40756
T:393103; 24000/40756
T:393110; 25000/40756
T:393119; 26000/40756
T:393129; 27000/40756
T:393136; 28000/40756
T:393144; 29000/40756
T:393177; 30000/40756
T:393190; 31000/40756
T:393198; 32000/40756
T:393208; 33000/40756
T:393217; 34000/40756
T:393225; 35000/40756
T:393233; 36000/40756
T:393241; 37000/40756
T:393249; 38000/40756
T:393260; 39000/40756
T:393267; 40000/40756
T:393411;  write checksum
T:393411; finish
[log] [2019-10-26T02:24:42.842Z] Summary of scrape actions: {
	"files": {
		"success": 207982,
		"fail": 1281
	},
	"articles": {
		"success": 3083055,
		"fail": 3428
	},
	"redirects": {
		"written": 4324589
	}
}
[log] [2019-10-26T02:24:42.843Z] Finished dump
[log] [2019-10-26T02:24:42.843Z] Closing HTTP agents...
[log] [2019-10-26T02:24:42.843Z] All dumping(s) finished with success.
[log] [2019-10-26T02:24:42.848Z] Flushing Redis DBs
Finished running mwoffliner after [407480s]
[log] [2019-10-26T02:24:42.851Z] Exiting with code [0]
[log] [2019-10-26T02:24:42.851Z] Deleting temporary directory [/tmp/mwoffliner-1571649206894]
```

**Comment by kelson42** [comment]
The root problem is handle in https://github.com/openzim/mwoffliner/issues/993. I will close that one as duplicate. @Popolechien Thx for reporting it.
