### ISSUE TITLE
New  request: 

### ISSUE THREAD

**Issue by waeq17** [openzim/zim-requests#595]
- Website URL: https://en.uesp.net
- License: Attribution-ShareAlike 2.5 License
- Desired ZIM Title: UESP Archive
- Desired ZIM Description: Unofficial Elder Scrolls Pages 
- Desired ZIM Icon –png (URL or attach one): 
![UESPWiki - The Unofficial Elder Scrolls Pages — Mozilla Firefox](https://user-images.githubusercontent.com/127051856/229385876-41900e32-620e-48d6-9f59-803f700fe2f5.png)
- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

**Comment by 07416** [comment]
seemingly a duplicate: https://github.com/openzim/zim-requests/issues/383

**Comment by D-side** [comment]
Was meaning to inquire the status of this but decided to see what I can gather on my own first

My understanding is that this is the recipe for it: https://farm.openzim.org/recipes/elder-scrolls-wiki
And the last run for it was 3 years ago: https://farm.openzim.org/pipeline/80ef091e-f618-43eb-a6b1-641f79b67f3b
…and it ended with:
```
[error] [2023-05-25T07:02:24.734Z] Failed to run mwoffliner after [5s]: {
	"stack": "Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.setBaseUrls (file:///tmp/mwoffliner/lib/Downloader.js:172:19)\n    at Module.execute (file:///tmp/mwoffliner/lib/mwoffliner.lib.js:134:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
	"message": "Unable to find appropriate API end-point to retrieve article HTML"
}
```

This seems to be a known problem that has been worked around: https://github.com/openzim/mwoffliner/issues/1975 using `--mwRestApiPath="/wiki/"`

Is there anything else in the way of this?

**Comment by Popolechien** [comment]
Updated recipe to https://farm.openzim.org/recipes/uesp.net_en_all, created CMS entry at https://cms.openzim.org/title/uesp.net_en_all and started a run.

**Comment by D-side** [comment]
It broke at 92.2% 🥲
Seemingly through no fault of the scraper, the page where it failed, https://en.uesp.net/wiki/Beyond_Skyrim:Testpage, breaks when opened normally as well, this is probably something to let UESP admins know.
…although, given the name, this doesn't seem like a content page that needs to be in a snapshot anyway? Could that specific page perhaps be skipped on the off chance it's the only one like that?

**Comment by D-side** [comment]
@waeq17 @xXTheCoolGamerXx @IronSim @wolfweim (authors of requests for UESP) hi, sorry to bother, do any of you by chance frequent UESP and can let the admins know about the broken `Beyond Skyrim:Testpage` to see if they could get the issue resolved? The breakage is complete and pretty gnarly, with a fully exposed stack trace, complete with system paths.

**Comment by benoit74** [comment]
Relaunched with this page ignored

**Comment by D-side** [comment]
Seems to have worked fine: https://staging.library.kiwix.org/viewer#uesp.net_en_all_maxi_2026-08

Job: https://farm.openzim.org/pipeline/7d7377a5-c55d-4c1f-9488-9a45c9d73241

`zimcheck` has found some redundancies and dangling links that probably need to be looked at, but this seems to be in the very least a somewhat usable file. Which is a lot more than there was!

**Comment by Popolechien** [comment]
I only get the landing page, all other links seem to be flagged as external, even when they're not. They seem to have been doing an extensive use of namespaces, but special:namespaceinfo isn't responding so I wouldn't know where to look for a full list.

<img width="1315" height="705" alt="Image" src="https://github.com/user-attachments/assets/440979c1-6e33-4d32-a639-d96bffc7717f" />

**Comment by D-side** [comment]
Oh, yeah, that's true, all the links lead back to the original website. Still, the pages and the content are there, search works too. So it already works for, say, looking up the book contents on devices where they render poorly in-game. But yeah, nowhere near ready for publishing in the main library.

**Comment by D-side** [comment]
@Popolechien would [this](https://en.uesp.net/w/api.php?action=query&meta=siteinfo&siprop=namespaces&format=json) (or [formatted](https://en.uesp.net/w/api.php?action=query&meta=siteinfo&siprop=namespaces&format=jsonfm)) help?

**Comment by Popolechien** [comment]
@benoit74 WDYT?
