### ISSUE TITLE
Wikinews in Gungbe

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#629]
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: http://guw.wikinews.org/
- License: **Creative Commons** 
- Desired ZIM Title: **Wikilinlin**
- Desired ZIM Description: **Adà Wikilinlin tọn he ma tin to intẹnẹt ji to Gungbe mẹ**
- Desired ZIM Icon –png (URL or attach one): 
- Language (ISO 639-3): **guw**
- Is this a MediaWiki?: **yes **

**Comment by RavanJAltaie** [comment]
Recipe created
https://farm.openzim.org/recipes/guw.wikinews_guw_all
I'll place the library file here once ready

**Comment by RavanJAltaie** [comment]
@benoit74 
This recipe is failing with this error:
```
(node:13) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[error] [2024-05-27T15:00:53.366Z] Failed to run mwoffliner after [2s]: {
	"stack": "Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.setBaseUrls (file:///tmp/mwoffliner/lib/Downloader.js:172:19)\n    at Module.execute (file:///tmp/mwoffliner/lib/mwoffliner.lib.js:134:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
	"message": "Unable to find appropriate API end-point to retrieve article HTML"
}
[error] [2024-05-27T15:00:53.367Z] 

**********

Unable to find appropriate API end-point to retrieve article HTML

**********



```

The prefix of the language is guw, while the only related language in language list in zimfarm in Gun (Gungbe). Is this related to the error?

**Comment by kelson42** [comment]
@RavanJAltaie We have dozens of working Wikinews recipes! Ensure you configure this recipe the same way and pretty sure it will work.

**Comment by benoit74** [comment]
URL is not correct, `http://guw.wikinews.org/` is automatically redirecting to `https://guw.wikinews.org/` (https instead of http), so you must use https URL for proper scraper operation.

**Comment by kelson42** [comment]
@benoit74 @Popolechien This works now, but we have a duplication of the recipe! And maybe of the ZIM files! See https://farm.openzim.org/recipes?name=wikinews_g

This should be fixed and then we can close this issue IMHO.

**Comment by benoit74** [comment]
I've deleted https://farm.openzim.org/recipes/guw.wikinews_guw_all in favor of https://farm.openzim.org/recipes/wikinews_guw

ZIM file names where colliding so we do not have duplicate ZIMs.
