### ISSUE TITLE
New request: bulbapedia.bulbagarden.net

### ISSUE THREAD

**Issue by Olfandik** [openzim/zim-requests#783]
- Website URL: https://bulbapedia.bulbagarden.net/
- License: Creative Commons Attribution-NonCommercial-ShareAlike
- Desired ZIM Title: Bulbapedia
- Desired ZIM Description: Bulbapedia, Pokémon Encyclopedia
- Desired ZIM Icon –png (URL or attach one): https://bulbapedia.bulbagarden.net/favicon.ico
- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

I would like an updated complete zim (with pics and vids) of the site. I know there is one at https://library.kiwix.org/ but it's outdated.

**Comment by RavanJAltaie** [comment]
@benoit74 we have this recipe [here](https://farm.openzim.org/recipes/bulbagarden). It's old and failing for long time. then disabled
the error is: 
> Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.setBaseUrls (file:///tmp/mwoffliner/lib/Downloader.js:172:19)\n    at Module.execute (file:///tmp/mwoffliner/lib/mwoffliner.lib.js:134:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
Can we fix it? shall we create a new recipe?

**Comment by benoit74** [comment]
Not until something is changed in mwoffliner. I've added the Upstream tag.

I don't open an issue because it looks like a known issue to me, maybe already solved in upcoming release.

**Comment by Rexadev** [comment]
This is a good example by Library needs Categories, this belongs to Entertainment>Fandom. 
Also there is Philology>Religion, Science>Computer/Biology/Maths

**Comment by Popolechien** [comment]
@Rexadev Just for the record your point is taken and there's already an ongoing discussion internally regarding categories and tagging.

**Comment by kelson42** [comment]
New attempt with MWoffliner `1.16.0`, see https://farm.openzim.org/pipeline/f39fa7a7-c595-4fe3-99a0-3b316524529a

**Comment by Popolechien** [comment]
LGTM - moving to PROD.

**Comment by Popolechien** [comment]
Ah never mind it already is available.

**Comment by benoit74** [comment]
Reopening because I realize that ZIM name is incorrect. It must be `bulbapedia.bulbagarden.net_en_all` instead of `bulbagarden_en_all`

Should be fixed on Zimfarm at https://farm.openzim.org/recipes/5fffb45d-9dfe-45f1-ac27-e40ec4a1b3e1 (set ZIM name flag, optionally update recipe name) and on CMS at https://cms.openzim.org/title/d4b3b5a2-3b86-4fc7-a6ab-77975858ba16

I don't mind if we do not rerun the recipe immediately, but at least we should fix the situation in CMS so that catalog is correct, and fix the Zimfarm recipe so that next ZIM is gonna be fine.

**Comment by Popolechien** [comment]
I have updated both CMS and zimfarm recipe - please confirm:
https://farm.openzim.org/recipes/bulbapedia.bulbagarden.net_en_all/edit
https://cms.openzim.org/title/bulbapedia.bulbagarden.net_en_all

**Comment by benoit74** [comment]
LGTM, thank you
