### ISSUE TITLE
wikihow_en_endless is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#796]
https://farm.openzim.org/pipeline/6fecfd46-0453-4a6c-84ff-d8f20115e77f has failed.

Error is:

```
[MainThread::2024-01-19 09:22:43,868] ERROR:FAILED. An error occurred: Object of type Response is not JSON serializable
[MainThread::2024-01-19 09:22:43,868] ERROR:Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 973, in run
    self.build_expected_articles()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 358, in build_expected_articles
    for query in self.api_site.query(
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/Site.py", line 310, in iterate
    result = self(action, **req)
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/Site.py", line 130, in __call__
    response = self.request(method, **request_kw)
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/Site.py", line 423, in request
    raise ApiError('Call failed', r)
pywikiapi.utils.ApiError: <unprintable ApiError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/entrypoint.py", line 225, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 1007, in run
    logger.error(f"Interrupting process due to error: {exc}")
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/utils.py", line 15, in __str__
    return self.message + ': ' + json.dumps(self.data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
```

I will open an upstream issue to investigate, this is a scraper problem.

**Comment by RavanJAltaie** [comment]
Since the troubleshooting is happening on another repository, I'll close the issue here.

**Comment by benoit74** [comment]
Nope, see https://github.com/openzim/zim-requests/issues/797#issuecomment-1934091065
