### ISSUE TITLE
wikihow_tr_maxi is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#797]
https://farm.openzim.org/pipeline/be343f7b-63e5-4f8c-900b-75af08cdf8f8 is failing

Error is:
```
[MainThread::2023-10-28 17:20:26,931] INFO:Ensuring source site DOM Integrity
[MainThread::2023-10-28 17:20:26,932] DEBUG:> checking CategoryListing
[MainThread::2023-10-28 17:20:27,300] WARNING:PAUSING requests for 15min
[MainThread::2023-10-28 17:20:27,303] ERROR:FAILED. An error occurred: #content_wrapper not found
[MainThread::2023-10-28 17:20:27,303] ERROR:#content_wrapper not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/entrypoint.py", line 225, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 911, in run
    self.check_dom_integrity()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 841, in check_dom_integrity
    raise DomIntegrityError("#content_wrapper not found")
wikihow2zim.scraper.DomIntegrityError: #content_wrapper not found
```

I will open an upstream issue, this looks like a scraper problem.

**Comment by RavanJAltaie** [comment]
Since the troubleshooting is happening on another repository, I'll close the issue here.

**Comment by benoit74** [comment]
Again, again, again: **NO, this MUST be kept open for now**

As per our [Policy](https://wiki.openzim.org/wiki/Content_team#Content_Requests):

```
Content requests should be closed:
- when fully implemented (user visible)
- if refusal or impossibility of implementation
```

**Comment by benoit74** [comment]
It has been decided that zim-request must contain only new requests, so this indeed has to be closed, sorry about that.
