### ISSUE TITLE
New request: GameFaq’s SNES

### ISSUE THREAD

**Issue by wachuwamekil** [openzim/zim-requests#828]
- Website URL: https://gamefaqs.gamespot.com/snes/category/999-all
- License: Public domain
- Desired ZIM Title: GameFaqs - SNES Games
- Desired ZIM Description: a backup of snes gamefaqs data
- Desired ZIM Icon –png (URL or attach one): 
https://logos.fandom.com/wiki/GameFAQs?file=Gamefaqs1999.gif
- Language (ISO 639-3): ISO 639-3
- Is this a MediaWiki?: No

**Comment by wachuwamekil** [comment]
On this request really the goal would be to focus on the guides section of each game list.  

URL is 
<base url>/<system>/<id-game name>/faqs

then scrap and save that content most are very small.

**Comment by RavanJAltaie** [comment]
The recipe is created
https://farm.openzim.org/recipes/gamefaqs.gamespot_en_all
I'll post the library link here once ready

**Comment by RavanJAltaie** [comment]
@benoit74 the recipe is taking so long, I've canceled once and re run again, but the same it's been 3 days 
can you please check?
https://farm.openzim.org/recipes/gamefaqs.gamespot_en_all

**Comment by RavanJAltaie** [comment]
The recipe failed with this error:
````
Traceback (most recent call last):  File "/usr/bin/zimit", line 566, in <module>    zimit()  File "/usr/bin/zimit", line 437, in zimit    raise subprocess.CalledProcessError(crawl.returncode, cmd_args)subprocess.CalledProcessError: Command '['crawl', '--failOnFailedSeed', '--waitUntil', 'load', '--title', 'GameFaqs - SNES Games', '--description', 'A backup of snes gamefaqs data', '--depth', '-1', '--timeout', '90', '--scopeType', 'host', '--lang', 'eng', '--behaviors', 'autoplay,autofetch,siteSpecific', '--behaviorTimeout', '90', '--diskUtilization', '90', '--url', 'https://gamefaqs.gamespot.com/snes/category/999-all', '--userAgent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15 +Zimit contact+zimfarm@kiwix.org', '--cwd', '/output/.tmpzx85wwer', '--statsFilename', '/output/crawl.json']' returned non-zero exit status 9.
````
@benoit74 any idea please?

**Comment by wachuwamekil** [comment]
Not sure if this will be helpful but I have a bit of a page breakdown here, I'm not sure the logic used for scraping files but It may be hanging on the videos for each game those are potentially 3 - 10 hour long "lets plays" for each game.

Each game may or may not have these items, but the primary information for each item is listed on the "all" page.  Guides, Cheats, saves, reviews, Q&A, Images, Videos, and the BBS.  I feel we can safely ignore videos and the board discussion as those can get huge.  I have broken how I was thinking when I put the request in.

base_url = https://gamefaqs.gamespot.com/

All Category
	- Game Name
		- Home:Summary (scrape page, don't follow links)
			URL == <base url>/snes/<id>-<game_name>
		- Home:Release Data (scrape page, don't follow links)
			URL == <base url>/snes/<id>-<game_name>/data
		- Home:Credits (scrape page, don't follow links)
			URL == <base url>/snes/<id>-<game_name>/credits
		- Home:Also Playing (scrape page, don't follow links)
			URL == <base url>/snes/<id>-<game_name>/playing
		- Guides: (scrap page, follow guide links to save/archive)
			URL == <base url>/snes/<id>-<game_name>/faqs
			- Guides are typically text, save these
		- Q&A: (scrape page, follow link to question answer, do not follow links on the question page)
			URL == <base url>/snes/<id>-<game_name>/answers
		- Reviews: (scrap page, don't follow links)
			URL == <base url>/snes/<id>-<game_name>/reviews
		- Cheats: (scrape page, don't follow links)
			URL == <base url>/snes/<id>-<game_name>/cheats
		- Media: boxes (scrape page, just the first page of images don't follow to page 2)
			URL == <base url>/snes/<id>-<game_name>/boxes
		- Screenshots (scrape page, just the first page of images don't follow to page 2)
			URL == <base url>/snes/<id>-<game_name>/images?pid=<id>&page=1
		- saves (scrap data here if its there should be small
			URL == <base url>/snes/<id>-<game_name>/saves
		- videos (ignore, potentially large hour long videos that can end up being huge)
		- board (ignore)

**Comment by benoit74** [comment]
>  the recipe is taking so long, I've canceled once and re run again, but the same it's been 3 days
can you please check?

What did you checked? The scraper found 380420 pages to process, if we say each page takes 1 minute to be saved (conservative value, might be a little less), it gives us 105 hours or 4 days. When you posted this message, the only thing which should have warned you is this big number: 380420 pages. @wachuwamekil explicitely said it should be small ... something is definitely not configured properly !!!

> On this request really the goal would be to focus on the guides section of each game list.
>
>URL is
>base url/system/id-game name/faqs
>
>then scrap and save that content most are very small.

This is not what has been configured. There is no include / exclude rule and scope has been set to `host`, so everything in https://gamefaqs.gamespot.com/ will be scraped! This is a nonsense for such a huge website and not in line with user request.

@wachuwamekil thank you for you detailed analysis on last comment. I don't think that it is really possible to do exactly what you've asked, but almost. What is not possible for instance is to scrape only image first page and not follow on page 2. We also cannot say "do not follow links" on a given page. But we will give the exact rule of which links can be followed, so somehow it will match your goal I think. To specify which link have to be followed, we have an include regular expression and an exclude one. These two rules apply on which page have to be visited. All resources on a given page (pictures, ...) will be saved.

If I've analyzed the website page structure well, and given how the scraper work, I propose following configuration:
- url: `https://gamefaqs.gamespot.com/snes/category/999-all` (ensure we get all games)
- scope: `custom` (only use specific include and exclude rules below)
- include: `https:\/\/gamefaqs\.gamespot\.com\/snes\/`
- exclude: `https:\/\/gamefaqs\.gamespot\.com\/snes\/.*\/videos`

So basically if I rephrase this: start from the `https://gamefaqs.gamespot.com/snes/category/999-all`, visit all pages which match the `https:\/\/gamefaqs\.gamespot\.com\/snes\/` regexp but ignore the ones matching `https:\/\/gamefaqs\.gamespot\.com\/snes\/.*\/videos`. I did not ignored `boards` explicitely since they are anyway somewhere else in the URL structure. I did not ignored links pointing somewhere outside the snes category or outside the website, they are already not included.

I also updated some other settings:
- ZIM filename and recipe name `gamefaqs.gamespot_en_all` => `gamefaqs.gamespot_en_snes` (we are scraping only the `snes` section of gamefaqs.gamespot.com
- Title: `GameFaqs - SNES Games` => `GameFAQs - SNES` (match case of official website, no need to repeat Games twice)
- Description: `A backup of snes gamefaqs data` => `GamesFAQs SNES games guides, cheats, Q&A, reviews, boxes, saves & screenshots` (all ZIMs are a kind of backup, no need to repeat it in every description, it does not help the ZIM user to decide if it is the ZIM he wants or not)
- Content Creator: was blank, set to `Fandom`
- ideally I would have added a `novid` flavor, since we might consider to include videos in another ZIM at some point, but this is not yet feasible with the current scraper.

**Comment by benoit74** [comment]
New recipe link: https://farm.openzim.org/recipes/gamefaqs.gamespot_en_snes

**Comment by benoit74** [comment]
I've requested the recipe, but there is a very important point which has been completely omitted: AFAIK, the license is not public domain, at least the footer says `© 2024 FANDOM, INC. ALL RIGHTS RESERVED.` and the `Terms of Use` link is pretty clear: https://www.fandom.com/terms-of-service-pp1

**Comment by benoit74** [comment]
I've stopped the Zimfarm task, the webserver has identified us as a bot and blocked every request.

Let's wait for next scraper release with browsertrix crawler 1.0 to see if it makes a change.

**Comment by RavanJAltaie** [comment]
@benoit74 Thanks for your efforts, can we mark the issue as upstream for now?

**Comment by wachuwamekil** [comment]
I really appreciate the effort here guys, I apologize if I misspoke on size. From a number standpoint There are around 2,400 listed games, not all have guides or the full level detail. 

There was more data on Final Fantasy than many games because of it's popularity.  It is however mostly text, assuming worst case all games had as much as FF3 had it would be about 48G of data in guides alone.  I thought it was way smaller than that tbh, and I apologize if I misrepresented that aspect.

**Comment by benoit74** [comment]
> Thanks for your efforts, can we mark the issue as upstream for now?

Sure, I just forgot to do it

> I really appreciate the effort here guys, I apologize if I misspoke on size

I don't think there is a size issue or that you misspoke about it. The scraper found 380420 pages to process because it was miss-configured and scraped all website pages (including videos, all consoles) instead of just SNES without videos (or even only guides as you originally asked for).
