### ISSUE TITLE
wikipedia_bn_all is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#866]
Recipe: https://farm.openzim.org/recipes/wikipedia_bn_all

```
[error] [2024-03-10T14:03:45.047Z] Error parsing article ওয়েব_উন্নয়নকারী
[error] [2024-03-10T14:03:45.048Z] Failed to run mwoffliner after [143s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at interpolateTranslationString (file:///tmp/mwoffliner/lib/util/misc.js:139:31)\n    at templateArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:860:21)\n    at processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:389:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)\n    at async Promise.all (index 0)\n    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:147:30",
	"message": "Cannot read properties of undefined (reading 'replace')"
}
```

Looks like it is impacted by this bug: https://github.com/openzim/mwoffliner/issues/1998

**Comment by kelson42** [comment]
It's back (with ActionParase) https://farm.openzim.org/recipes/wikipedia_bn_all
