### ISSUE TITLE
wikipedia_sh_top has improper language

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#889]
Recipe: https://farm.openzim.org/recipes/wikipedia_sh_top

```
[error] [2024-03-13T12:02:11.613Z] Failed to run mwoffliner after [1s]: {
	"stack": "Error: MetaData Language: must match pattern \"^\\w{3}(,\\w{3})*$\"\n    at validateMetadata (file:///tmp/mwoffliner/lib/util/metaData.js:53:15)\n    at Module.execute (file:///tmp/mwoffliner/lib/mwoffliner.lib.js:127:5)",
	"message": "MetaData Language: must match pattern \"^\\w{3}(,\\w{3})*$\""
}
[error] [2024-03-13T12:02:11.614Z] 

**********

MetaData Language: must match pattern "^\w{3}(,\w{3})*$"

**********
```

I disabled the recipe until language is fixed (proper value must be forced manually in the recipe).

**Comment by kelson42** [comment]
It pass now... but I believe this is still not correct, but this is already tracked at https://github.com/openzim/zim-requests/issues/1430
