### ISSUE TITLE
wikipedia_scn_all is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#890]
Recipe: https://farm.openzim.org/recipes/wikipedia_scn_all

```
[error] [2024-03-13T17:02:23.498Z] Error parsing article 1053
[error] [2024-03-13T17:02:23.498Z] Failed to run mwoffliner after [15s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at interpolateTranslationString (file:///tmp/mwoffliner/lib/util/misc.js:139:31)\n    at templateArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:860:21)\n    at processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:389:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)\n    at async Promise.all (index 0)\n    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:147:30",
	"message": "Cannot read properties of undefined (reading 'replace')"
}
[error] [2024-03-13T17:02:23.499Z] 

**********

Cannot read properties of undefined (reading 'replace')

**********
```

Upstream issue: https://github.com/openzim/mwoffliner/issues/1998

I disabled the recipe.

**Comment by kelson42** [comment]
Has been updated with success, see https://farm.openzim.org/pipeline/1cb7a6ac-582b-4282-b0a8-438084c06745
