### ISSUE TITLE
wikipedia_nds-nl_all has improper language

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#892]
Recipe : https://farm.openzim.org/recipes/wikipedia_nds-nl_all

```
(node:13) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[error] [2024-03-13T18:01:07.938Z] Failed to run mwoffliner after [2s]: {
	"stack": "Error: MetaData Language: must match pattern \"^\\w{3}(,\\w{3})*$\"\n    at validateMetadata (file:///tmp/mwoffliner/lib/util/metaData.js:53:15)\n    at Module.execute (file:///tmp/mwoffliner/lib/mwoffliner.lib.js:123:5)",
	"message": "MetaData Language: must match pattern \"^\\w{3}(,\\w{3})*$\""
}
[error] [2024-03-13T18:01:07.938Z] 

**********

MetaData Language: must match pattern "^\w{3}(,\w{3})*$"

**********
```

I disabled the recipe until language is fixed (proper value must be forced manually in the recipe).

**Comment by kelson42** [comment]
This has been fixed, see https://farm.openzim.org/recipes/wikipedia_nds-nl_all
