### ISSUE TITLE
wikinews_fi is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#903]
Recipe: https://farm.openzim.org/recipes/wikinews_fi

```
[error] [2024-03-14T14:01:16.761Z] Error parsing article Atlantis-avaruussukkulan_laukaisu_siirtyi_jälleen
[error] [2024-03-14T14:01:16.762Z] Failed to run mwoffliner after [5s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at interpolateTranslationString (file:///tmp/mwoffliner/lib/util/misc.js:139:31)\n    at templateArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:860:21)\n    at processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:389:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)\n    at async Promise.all (index 0)\n    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:147:30",
	"message": "Cannot read properties of undefined (reading 'replace')"
}
[error] [2024-03-14T14:01:16.762Z] 

**********

Cannot read properties of undefined (reading 'replace')

**********
```

Upstream issue: https://github.com/openzim/mwoffliner/issues/1998

I disabled the recipe for now.

**Comment by benoit74** [comment]
Last task is OK : https://farm.openzim.org/pipeline/7b1ef70b-1f83-4c87-b236-70cbc060698e
