### ISSUE TITLE
wikiquote_br is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#912]
Recipe: https://farm.openzim.org/recipes/wikiquote_br

```
[error] [2024-03-17T16:26:43.034Z] Error parsing article Blaise_Pascal
[error] [2024-03-17T16:26:43.035Z] Failed to run mwoffliner after [4s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at interpolateTranslationString (file:///tmp/mwoffliner/lib/util/misc.js:139:31)\n    at templateArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:860:21)\n    at processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:389:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)\n    at async Promise.all (index 0)\n    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:147:30",
	"message": "Cannot read properties of undefined (reading 'replace')"
}
[error] [2024-03-17T16:26:43.035Z] 

**********

Cannot read properties of undefined (reading 'replace')

**********
```

Upstream issue: https://github.com/openzim/mwoffliner/issues/1998

I disabled the recipe for now.

**Comment by benoit74** [comment]
Last task is OK: https://farm.openzim.org/pipeline/25e0ea5b-0550-47ee-a119-6f1a49a3fae6
