### ISSUE TITLE
wikivoyage_bn has failed

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#918]
Recipe: https://farm.openzim.org/recipes/wikivoyage_bn

```
[error] [2024-03-17T11:13:58.785Z] Error parsing article সোনাদিয়া_দ্বীপ
[error] [2024-03-17T11:13:58.786Z] Failed to run mwoffliner after [3s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at interpolateTranslationString (file:///tmp/mwoffliner/lib/util/misc.js:139:31)\n    at templateArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:860:21)\n    at processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:389:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)\n    at async Promise.all (index 0)\n    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:147:30",
	"message": "Cannot read properties of undefined (reading 'replace')"
}
[error] [2024-03-17T11:13:58.786Z] 

**********

Cannot read properties of undefined (reading 'replace')

**********
```

Upstream issue: https://github.com/openzim/mwoffliner/issues/1998

 I disabled the recipe

**Comment by kelson42** [comment]
works now with dev version of MWoffliner https://farm.openzim.org/pipeline/739b9461-05d6-4860-9f7a-773d9ade993e

**Comment by benoit74** [comment]
Indeed, file is in prod now: https://library.kiwix.org/#lang=ben&q=Wikivoyage
