### ISSUE TITLE
wikibooks_fi is failing

### ISSUE THREAD

**Issue by benoit74** [openzim/zim-requests#935]
### Recipe URL

https://farm.openzim.org/recipes/wikibooks_fi

### Last log lines

```true
[error] [2024-03-25T09:01:50.682Z] Error parsing article Shakkitermit/Pitkä_linnoitus
[error] [2024-03-25T09:01:50.683Z] Failed to run mwoffliner after [17s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at interpolateTranslationString (file:///tmp/mwoffliner/lib/util/misc.js:139:31)\n    at templateArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:860:21)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:389:24)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)\n    at async Promise.all (index 0)\n    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:147:30",
	"message": "Cannot read properties of undefined (reading 'replace')"
}
[error] [2024-03-25T09:01:50.683Z] 

**********

Cannot read properties of undefined (reading 'replace')

**********
```

### How many times the recipe failed in a row?

Many

### How many ZIM have been produced before failure?

Zero

### Which action did you undertake so far?

I have disabled the recipe for now

### What's next?

This is an upstream scraper problem

### More details

Upstream issue: https://github.com/openzim/mwoffliner/issues/1998

**Comment by benoit74** [comment]
Last task completed correctly: https://farm.openzim.org/pipeline/468f915d-9ab6-451f-94d0-5ec132322101
