### ISSUE TITLE
ZIM file of wikispooks

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#99]
_From @kelson42 on October 24, 2016 10:27_

https://wikispooks.com/wiki/Main_Page

_Copied from original issue: openzim/mwoffliner#29_

**Comment by kelson42** [comment]
A mediawiki upgrade is needed first.

**Comment by kelson42** [comment]
Seems to fail quite at the beginning, @ISNIT0 any clue?

```
$ mwoffliner --mwUrl="https://wikispooks.com/" --adminEmail="kelson@kiwix.com" --localParsoid --verbose
Starting Parsoid
info loading ...
info ready on :8000
Parsoid Started Successfully
Getting text direction...
Downloading https://wikispooks.com/wiki/...
Text direction is ltr
Getting web site name...
Downloading https://wikispooks.com/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc...
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/mwoffliner/lib/MediaWiki.js:115:24
    at async.retry (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:176:7)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:676:51
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:723:17
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:167:37
```

**Comment by RavanJAltaie** [comment]
Requested.
The file will work after the mediawiki mwoffliner be updated.
https://farm.openzim.org/recipes/wikispooks
